# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQnxL4eQ-0zotbApFF72J4TrJmhDdGb7
"""

'''
Creació de funcions
Una funció és un bloc de codi reutilitzable que només s'executa quan el crides. Utilitzem la paraula clau def per definir-la.
Objectiu: Evitar repetir codi i fer el programa més net.
Sintaxi: def, nom de la funció, parèntesis () i dos punts :. Tot el codi de dins ha d'estar indentat.
'''
#Exemple: Funció que saluda

#Definició de la funció
def say_hello():
  print("Hello!")

#Crida de la funció
say_hello()

'''
Pas de paràmetres
Els paràmetres són variables que posem dins dels parèntesis. Permeten que la funció treballi amb dades diferents cada vegada que la cridem.
Paràmetre: El nom de la variable que farem servir a la funció (podem posar el nom que vulguem, però hem d'intentar que tingui coherència)
Argument: El valor real que passem quan la cridem.
Observació: L'ordre és important a la crida, cada espai indica la posició amb la qual la rep la funció
'''

#Exemple: Funció que saluda amb el nom de l'usuari i la seva edat

#Paràmetre: username, age
#Argument(valor real): Detectiu Conan,16

def say_hello_user(username, age):
  print(f"Hello {username}, you are {age} old.")

say_hello_user("Detectiu Conan", 16)

#ATENCIÓ!!!!
#També podem passar els arguments pel seu nom i l'ordre no importarà
#Exemple
say_hello_user(age=16,username="Detectiu Conan")

'''
Valor de retorn (return)
Diferència clau: print només mostra text a la pantalla (per a l'usuari). return retorna la dada al programa perquè la puguis guardar en una variable o fer càlculs posteriors
Regla: Quan Python llegeix un return, la funció s'acaba immediatament!
'''
#Exemple: Funció que calcula el preu final d'un producte

#Definició de la funció
def calculate_price(price, tax):
  total = price * tax
  return total

#Podem emmagatzemar el resultat en una variable
result = calculate_price(10,5)

print(f"El preu final és: {result}")

#Podem mostrar directament el valor en un print
print(f"El preu final és: {calculate_price(10,5)}")

#Podem avaluar el resultat en una estructura de control o repetició
if calculate_price(10,5) > 10:
  print("El preu és major a 10")
else:
  print("El preu és menor a 10")

'''
Funcions amb valors per defecte
Pots fer que certs paràmetres siguin opcionals assignant-los un valor inicial amb =
Regla: Els paràmetres amb valor per defecte han d'anar sempre al final, després dels obligatoris
'''
#Exemple: Funció que mostra un preu amb la unitat monetària

#Indiquem el valor per defecte del paràmetre currency
def display_price(price, currency="€"):
  print(f"El preu és {price}{currency}")

#Fem servir el valor per defecte €
display_price(10)

#Modifiquem el valor per defecte a $
display_price(10,"$")